ERROR: m7Bc3pLyij0: YouTube said: Unable to extract video data
Ignoring exception in command play:
Traceback (most recent call last):
  File "C:\Users\Marvin\AppData\Local\Programs\Python\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Marvin\AppData\Local\Programs\Python\Python37\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Marvin\AppData\Local\Programs\Python\Python37\lib\site-packages\youtube_dl\extractor\youtube.py", line 1836, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: m7Bc3pLyij0: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Marvin\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Marvin\PycharmProjects\HQGdicordbot\cogs\Music.py", line 115, in play
    player = await YTDLSource.from_url(url, loop=self.bot.loop)
  File "C:\Users\Marvin\PycharmProjects\HQGdicordbot\cogs\Music.py", line 61, in from_url
    data = await loop.run_in_executor(None, lambda: ytdl.extract_info(url, download=not stream))
  File "C:\Users\Marvin\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Marvin\PycharmProjects\HQGdicordbot\cogs\Music.py", line 61, in <lambda>
    data = await loop.run_in_executor(None, lambda: ytdl.extract_info(url, download=not stream))
  File "C:\Users\Marvin\AppData\Local\Programs\Python\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Marvin\AppData\Local\Programs\Python\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 869, in process_ie_result
    extra_info=extra_info)
  File "C:\Users\Marvin\AppData\Local\Programs\Python\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 807, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Marvin\AppData\Local\Programs\Python\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 1007, in process_ie_result
    extra_info=extra)
  File "C:\Users\Marvin\AppData\Local\Programs\Python\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 869, in process_ie_result
    extra_info=extra_info)
  File "C:\Users\Marvin\AppData\Local\Programs\Python\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 819, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\Marvin\AppData\Local\Programs\Python\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Marvin\AppData\Local\Programs\Python\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: m7Bc3pLyij0: YouTube said: Unable to extract video data

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Marvin\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Marvin\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Marvin\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: DownloadError: ERROR: m7Bc3pLyij0: YouTube said: Unable to extract video data
